// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, user_id, created_at, updated_at, start_date, end_date, title, description, priority, recur_d, recur_w, recur_m, recur_y)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, created_at, updated_at, start_date, end_date, title, description, priority, recur_d, recur_w, recur_m, recur_y
`

type CreateEventParams struct {
	UserID      uuid.UUID
	StartDate   time.Time
	EndDate     time.Time
	Title       string
	Description sql.NullString
	Priority    bool
	RecurD      bool
	RecurW      bool
	RecurM      bool
	RecurY      bool
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.RecurD,
		arg.RecurW,
		arg.RecurM,
		arg.RecurY,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.RecurD,
		&i.RecurW,
		&i.RecurM,
		&i.RecurY,
	)
	return i, err
}

const deleteEventByID = `-- name: DeleteEventByID :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEventByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEventByID, id)
	return err
}

const deleteEvents = `-- name: DeleteEvents :exec
DELETE FROM events
`

func (q *Queries) DeleteEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEvents)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, user_id, created_at, updated_at, start_date, end_date, title, description, priority, recur_d, recur_w, recur_m, recur_y FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.RecurD,
		&i.RecurW,
		&i.RecurM,
		&i.RecurY,
	)
	return i, err
}

const getEventsByUserID = `-- name: GetEventsByUserID :many
SELECT id, user_id, created_at, updated_at, start_date, end_date, title, description, priority, recur_d, recur_w, recur_m, recur_y FROM events WHERE user_id = $1
`

func (q *Queries) GetEventsByUserID(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.EndDate,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.RecurD,
			&i.RecurW,
			&i.RecurM,
			&i.RecurY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    updated_at = NOW(),
    start_date = $1,
    end_date = $2,
    title = $3,
    description = $4,
    priority = $5,
    recur_d = $6,
    recur_w = $7,
    recur_m = $8,
    recur_y = $9
WHERE id = $10
RETURNING id, user_id, created_at, updated_at, start_date, end_date, title, description, priority, recur_d, recur_w, recur_m, recur_y
`

type UpdateEventParams struct {
	StartDate   time.Time
	EndDate     time.Time
	Title       string
	Description sql.NullString
	Priority    bool
	RecurD      bool
	RecurW      bool
	RecurM      bool
	RecurY      bool
	EventID     uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.StartDate,
		arg.EndDate,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.RecurD,
		arg.RecurW,
		arg.RecurM,
		arg.RecurY,
		arg.EventID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.RecurD,
		&i.RecurW,
		&i.RecurM,
		&i.RecurY,
	)
	return i, err
}
