// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	StartDate   time.Time
	EndDate     time.Time
	Title       string
	Description sql.NullString
	Priority    bool
	RecurD      bool
	RecurW      bool
	RecurM      bool
	RecurY      bool
}

type EventTag struct {
	EventID uuid.UUID
	TagID   uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

type Subscription struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	StripeCustomerID     string
	StripeSubscriptionID string
	Plan                 string
	Status               string
	CurrentPeriodStart   time.Time
	CurrentPeriodEnd     time.Time
	CancelAtPeriodEnd    bool
	CanceledAt           sql.NullTime
	TrialStart           sql.NullTime
	TrialEnd             sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Tag struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Color  string
}

type Todo struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Date        sql.NullTime
	Title       string
	Description sql.NullString
}

type User struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Username         string
	Email            string
	HashedPassword   string
	PhoneNumber      string
	StripeCustomerID sql.NullString
}
