# fly.toml app configuration file generated for taday-sms on 2025-06-27T13:23:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taday-sms'
primary_region = 'ewr'

[build]

[experimental]
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "sleep infinity"

[[services.timers]]
schedule = "0 8 * * *"
command = ["/usr/local/bin/taday-sms"]

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
